# Generated by Django 4.1.2 on 2023-07-07 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bacca", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="idPedido", primary_key=True, serialize=False
                    ),
                ),
                ("carrito", models.TextField()),
                ("total", models.IntegerField()),
                ("tipo_pago", models.CharField(max_length=20)),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="cliente",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
