# Generated by Django 4.1.2 on 2023-07-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bacca", "0002_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="estado",
            field=models.CharField(default="pendiente", max_length=20),
            preserve_default=False,
        ),
    ]
