# Generated by Django 4.1.2 on 2023-07-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bacca", "0003_pedido_estado"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormularioContacto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="idFormulario", primary_key=True, serialize=False
                    ),
                ),
                ("email", models.CharField(max_length=40)),
                ("solicitud", models.TextField()),
                ("suscrito", models.BooleanField()),
            ],
        ),
    ]
